In [3]:
import torch

In [421]:
words = open('names.txt').read().splitlines()

#print(words[:10])

b = {}
for w in words:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2, ch3 in zip(chs, chs[1:], chs[2:]):
      #print(ch1, ch2, ch3)
      trigram = (ch1, ch2, ch3)
      b[trigram] = b.get(trigram, 0) + 1

print(sorted(b.items(), key = lambda kv: -kv[1]))

N = torch.zeros((27, 27, 27), dtype=torch.int32)

chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}

for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2, ch3 in zip(chs, chs[1:], chs[2:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        ix3 = stoi[ch3]
        N[ix1, ix2, ix3] += 1


[(('a', 'h', '.'), 1714), (('n', 'a', '.'), 1673), (('a', 'n', '.'), 1509), (('o', 'n', '.'), 1503), (('.', 'm', 'a'), 1453), (('.', 'j', 'a'), 1255), (('.', 'k', 'a'), 1254), (('e', 'n', '.'), 1217), (('l', 'y', 'n'), 976), (('y', 'n', '.'), 953), (('a', 'r', 'i'), 950), (('i', 'a', '.'), 903), (('i', 'e', '.'), 858), (('a', 'n', 'n'), 825), (('e', 'l', 'l'), 822), (('a', 'n', 'a'), 804), (('i', 'a', 'n'), 790), (('m', 'a', 'r'), 776), (('i', 'n', '.'), 766), (('e', 'l', '.'), 727), (('y', 'a', '.'), 716), (('a', 'n', 'i'), 703), (('.', 'd', 'a'), 700), (('l', 'a', '.'), 684), (('e', 'r', '.'), 683), (('i', 'y', 'a'), 669), (('l', 'a', 'n'), 647), (('.', 'b', 'r'), 646), (('n', 'n', 'a'), 633), (('.', 'a', 'l'), 632), (('.', 'c', 'a'), 628), (('r', 'a', '.'), 627), (('n', 'i', '.'), 625), (('.', 'a', 'n'), 623), (('n', 'n', '.'), 619), (('n', 'e', '.'), 607), (('e', 'e', '.'), 605), (('e', 'y', '.'), 602), (('.', 'k', 'e'), 601), (('a', 'l', 'e'), 601), (('.', 's', 'a'), 595), (('a', 

In [272]:
print(N.shape)

torch.Size([27, 27, 27])


In [444]:
#smoothing to get rid of NaN
for elements in N:
    elements+= 1
N[0]

tensor([[   1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1],
        [   1,  208,  191,   32,  367,   56,   22,   18,   92,  155,   28,   76,
          633,  385,  624,   11,   18,   10,  483,  195,   73,  153,  244,    7,
           28,  174,  153],
        [   1,  170,    1,    1,    1,  254,    1,    1,   10,   42,    2,    1,
           86,    1,    1,   78,    1,    1,  647,    1,    1,   22,    1,    1,
            1,    5,    1],
        [   1,  629,    1,    1,    1,   66,    1,    1,  353,   45,    3,    1,
           69,    1,    1,  256,    1,    1,   68,    1,    1,   14,    1,    1,
            1,   47,    3],
        [   1,  701,    1,    1,    1,  525,    1,    1,   33,  131,    7,    3,
            3,   20,    4,  120,    1,    1,   78,    2,    1,   36,    4,    7,
            1,   32,    1],
        [   1,   24,   16,    5,   81,   10,   11,

In [450]:
p = N[0].float()
p = p / p.sum()
p


tensor([[3.0523e-05, 3.0523e-05, 3.0523e-05, 3.0523e-05, 3.0523e-05, 3.0523e-05,
         3.0523e-05, 3.0523e-05, 3.0523e-05, 3.0523e-05, 3.0523e-05, 3.0523e-05,
         3.0523e-05, 3.0523e-05, 3.0523e-05, 3.0523e-05, 3.0523e-05, 3.0523e-05,
         3.0523e-05, 3.0523e-05, 3.0523e-05, 3.0523e-05, 3.0523e-05, 3.0523e-05,
         3.0523e-05, 3.0523e-05, 3.0523e-05],
        [3.0523e-05, 6.3488e-03, 5.8299e-03, 9.7674e-04, 1.1202e-02, 1.7093e-03,
         6.7151e-04, 5.4942e-04, 2.8081e-03, 4.7311e-03, 8.5465e-04, 2.3198e-03,
         1.9321e-02, 1.1751e-02, 1.9046e-02, 3.3575e-04, 5.4942e-04, 3.0523e-04,
         1.4743e-02, 5.9520e-03, 2.2282e-03, 4.6700e-03, 7.4477e-03, 2.1366e-04,
         8.5465e-04, 5.3110e-03, 4.6700e-03],
        [3.0523e-05, 5.1889e-03, 3.0523e-05, 3.0523e-05, 3.0523e-05, 7.7529e-03,
         3.0523e-05, 3.0523e-05, 3.0523e-04, 1.2820e-03, 6.1046e-05, 3.0523e-05,
         2.6250e-03, 3.0523e-05, 3.0523e-05, 2.3808e-03, 3.0523e-05, 3.0523e-05,
         1.9748e-

In [452]:
N2 = torch.zeros((27, 27), dtype=torch.int32)
for x in range(27):
    for y in range(27):
        sum = 0
        for element in N[x, y]:
            sum += element
        N2[x, y] = sum

N2[0]

tensor([  27, 4437, 1333, 1569, 1717, 1558,  444,  696,  901,  618, 2449, 2990,
        1599, 2565, 1173,  421,  542,  119, 1666, 2082, 1335,  105,  403,  334,
         161,  562,  956], dtype=torch.int32)

In [459]:
p1 = N2[0].float()
p1 = p1 / p1.sum()
p1

tensor([0.0008, 0.1354, 0.0407, 0.0479, 0.0524, 0.0476, 0.0136, 0.0212, 0.0275,
        0.0189, 0.0748, 0.0913, 0.0488, 0.0783, 0.0358, 0.0129, 0.0165, 0.0036,
        0.0509, 0.0635, 0.0407, 0.0032, 0.0123, 0.0102, 0.0049, 0.0172, 0.0292])

In [453]:
p = N[0, 0].float()
p = p / p.sum()
p

tensor([0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370,
        0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370,
        0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370])

In [432]:
g = torch.Generator().manual_seed(2147483647)
p = torch.rand(3, generator=g)
p = p / p.sum()
print(p)

tensor([0.6064, 0.3033, 0.0903])


In [483]:
g = torch.Generator().manual_seed(2147483148)
ix = torch.multinomial(p1, num_samples=1, replacement=True, generator=g).item()
itos[ix]


'b'

In [433]:
samples = torch.multinomial(p, num_samples=100, replacement=True, generator=g)
samples

tensor([1, 1, 2, 0, 0, 2, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
        0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 1, 0,
        0, 1, 1, 1])

In [533]:
g = torch.Generator().manual_seed(2147483148)
for i in range(20):
    out = ""
    ix = 0
    ix2 = torch.multinomial(p1, num_samples=1, replacement=True, generator=g).item()
    out += (itos[ix2])
    while True:
        p = N[ix, ix2].float()
        p = p / p.sum()
        prediction = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
        out += (itos[prediction])
        if prediction == 0:
            break
        ix = ix2
        ix2 = prediction

    print(out)

bon.
mishannany.
beer.
eqwreerriaio.
ellarah.
dela.
ob.
keybrian.
gon.
cridestiah.
annaire.
jaiyahnaleiya.
jema.
na.
dena.
annabisate.
evalynnashon.
caya.
cari.
norver.
